Fix combo box shortcut key sequence for Qt 5.15.13
The previous code worked for Qt 6, but for me with Qt 5.15.13, I
received the following (with -Werror):

  /home/scott/lyxbuilds/master-master/repo/src/frontends/qt/GuiPrefs.cpp:1047:46: error: arithmetic between different enumeration types ('Qt::Modifier' and 'Qt::Key') is deprecated
  [-Werror,-Wdeprecated-enum-enum-conversion]
   1047 |                 new QShortcut(QKeySequence(Qt::CTRL + Qt::Key_L), this);
        |                                            ~~~~~~~~ ^ ~~~~~~~~~

If I changed the guard condition to be < 5.15.0 (so that the Qt 6
code path is triggered with Qt 5.15.13), I then get the following
different failure:

  /home/scott/lyxbuilds/master-master/repo/src/frontends/qt/GuiPrefs.cpp:1050:46: error: bitwise operation between different enumeration types ('Qt::Modifier' and 'Qt::Key') is deprecated
  [-Werror,-Wdeprecated-enum-enum-conversion]
    1050 |                 new QShortcut(QKeySequence(Qt::CTRL | Qt::Key_L), this);
         |                                            ~~~~~~~~ ^ ~~~~~~~~~

This commit fixes it by using an alternative form documented here:

  https://doc.qt.io/qtforpython-5/PySide2/QtGui/QKeySequence.html