Cmake build: turn off some warnings
-Wunreachable-code-return for src/LyX.cpp
  clang warning:
  	src/LyX.cpp:1245:9: warning: 'return' will never be executed [-Wunreachable-code-return]
		return 0;
	src/LyX.cpp:1258:9: warning: 'return' will never be executed [-Wunreachable-code-return]
		return 0;

and -Wsuggest-destructor-override src/EnchantChecker.cpp
  clang warning:
  	/usr/include/enchant-2/enchant++.h:55:12: error: '~Exception' overrides a destructor but is not marked 'override' [-Werror,-Wsuggest-destructor-override]
	   55 |                         virtual ~Exception () noexcept {
	      |                                 ^
	/usr/bin/../lib/gcc/x86_64-linux-gnu/14/../../../../include/c++/14/bits/exception.h:63:13: note: overridden virtual function is here
	   63 |     virtual ~exception() _GLIBCXX_TXN_SAFE_DYN _GLIBCXX_NOTHROW;
	      |             ^
since booth affected files are not part of to lyx-sources