Fix LATTEST() call and a -Wstring-conversion
LATTEST() expects an expression. This commit changes an
LATTEST(string) call to instead first give an error and then call
LATTEST(false).

Fixes the following warning:

src/frontends/qt/GuiInputMethod.cpp:383:11: error: implicit conversion turns string literal into bool: 'const char[53]' to 'bool' [-Werror,-Wstring-conversion]
  383 |                 LATTEST("Turnouts of preedit segments have not been all swept");
      |                 ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/support/lassert.h:83:6: note: expanded from macro 'LATTEST'
   83 |         if (expr) {} else { lyx::doAssert(#expr, __FILE__, __LINE__); }
      |         ~~  ^~~~

Amends 29d41c1e.